version: '3.8'

services:
  rag-bot:
    build: .
    container_name: rag_bot_container_yandex
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - YC_API_KEY=${YC_API_KEY}
      - YC_FOLDER_ID=${YC_FOLDER_ID}
    volumes:
      - ./vectorstore:/app/vectorstore
    restart: unless-stopped
